# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'J.YoutubeWatcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 5.0.0-beta.2'
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
  # Pods for J.YoutubeWatcher

  target 'J.YoutubeWatcherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'J.YoutubeWatcherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
